/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.netbeans.controls;

import java.io.File;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import study.netbeans.common.LoggerManager;

/**
 *
 * @author P088454
 */
public class FileChooserControls extends javax.swing.JFrame {
    private LoggerManager loggerMgr;    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FileChooserControls.class.getName());

    /**
     * Creates new form FileShooserControls
     */
    public FileChooserControls() {
        initLoggerManager();
        initComponents();
    }

    private void initLoggerManager() {
        loggerMgr = new LoggerManager(this.getClass().getName(), Level.INFO);
        loggerMgr.getLogger().info("===> initLoggerManager()");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        pathTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createButton.setText("생성");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        loadButton.setText("로드");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        pathTextField.setEditable(false);
        pathTextField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addGap(26, 26, 26)
                        .addComponent(loadButton)
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(loadButton))
                .addGap(18, 18, 18)
                .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        //JFileChooser chooser = new JFileChooser("C:\\Users\\User\\Documents"); 특정경로 설정
        // 디렉토리만 선택 가능
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setDialogTitle("생성");
        
        // ▼ 파일 유형(필터) 콤보 숨김
        // - swing에서 UI는 못없애고 필터만 제거 됨
        //chooser.resetChoosableFileFilters();      // 혹시 이전에 추가한 필터가 있으면 초기화
        chooser.setAcceptAllFileFilterUsed(false);// "모든 파일" 필터도 숨기기
        
        int result = chooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // 사용자가 "파일 이름" 입력칸에 폴더명을 입력하면 포함된 경로가 됨
            File newDir = chooser.getSelectedFile();
            loggerMgr.getLogger().info("newDir = " + newDir.toString());
            
//            if (folderName.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "폴더명을 입력하세요.");
//                return;
//            }

            if (newDir.exists() == false) {
                if (newDir.mkdirs() == true) {
                    pathTextField.setText(newDir.getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(this, "폴더 생성 실패");
                }
            } else {
                JOptionPane.showMessageDialog(this, "이미 폴더가 존재합니다.");
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        //JFileChooser chooser = new JFileChooser();
        JFileChooser chooser = new JFileChooser("C:\\Users\\P088454\\Desktop");
        //chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // 디렉토리만 선택
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); // 파일까지 다 보임
        chooser.setDialogTitle("로드");
        
        // ▼ 파일 유형(필터) 콤보 숨김
        // - swing에서 UI는 못없애고 필터만 제거 됨
        //chooser.resetChoosableFileFilters();      // 혹시 이전에 추가한 필터가 있으면 초기화
        chooser.setAcceptAllFileFilterUsed(false);// "모든 파일" 필터도 숨기기

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedDir = chooser.getSelectedFile();
            loggerMgr.getLogger().info("newDir = " + selectedDir.toString());
            
            pathTextField.setText("로드됨: " + selectedDir.getAbsolutePath());
            
            // 디렉토리 안의 파일 목록 읽기
            File[] files = selectedDir.listFiles();
            if (files != null) {
                //StringBuilder sb = new StringBuilder();
                for (File f : files) {
                    loggerMgr.getLogger().info("fileName = " + f.getName());
//                    sb.append(f.getName());
//                    if (f.isDirectory()) {
//                        sb.append(" [DIR]");
//                    } else {
//                        sb.append(" [FILE] ");
//                        sb.append(" size=").append(f.length()).append(" bytes");
//                    }
//                    sb.append("\n");
                }

                // 파일 목록을 다이얼로그에 출력 (테스트용)
//                JOptionPane.showMessageDialog(this, sb.toString());
            }
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FileChooserControls().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration//GEN-END:variables
}
