/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.netbeans.controls;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.util.SwingUtils;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import study.netbeans.common.logger.LoggerManager;
import study.netbeans.common.looandfeel.LookAndFeelManager;

/**
 *
 * @author a
 */
public class FramePanelControls extends javax.swing.JFrame {
    
    private LoggerManager loggerMgr;
    //private LookAndFeelManager lookAndFeelMgr;

    /**
     * Creates new form FrameControls_1
     */
    public FramePanelControls() {
        initLoggerManager();
        
        //initLookAndFeelManager();
        
        initComponents();
        
        initSevenList();
        
        loggerMgr.getLogger().info("FramePanelControls()");        
    }

    private void initLoggerManager() {
        loggerMgr = new LoggerManager(this.getClass().getName(), Level.INFO);
    }
    
    private void initSevenList() {
        DefaultListModel model = (DefaultListModel) sevenList1.getModel();
        //model.addElement(new String[] {"list_1","list_2","list_3","list_4"});
        model.addElement("list_1");
        model.addElement("list_2");
        model.addElement("list_3");
        model.addElement("list_4");
        model.addElement("list_5");
        model.addElement("list_6");
    }
    
//    private void initLookAndFeelManager() {
//        lookAndFeelMgr = new LookAndFeelManager(loggerMgr);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup1 = new javax.swing.ButtonGroup();
        toggleButtonGroup1 = new javax.swing.ButtonGroup();
        onePanel = new javax.swing.JPanel();
        oneLabel = new javax.swing.JLabel();
        oneTextField = new javax.swing.JTextField();
        oneButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        oneTextArea1 = new javax.swing.JTextArea();
        twoPanel = new javax.swing.JPanel();
        twoLabel = new javax.swing.JLabel();
        twoButton1 = new javax.swing.JButton();
        twoButton2 = new javax.swing.JButton();
        twoButton3 = new javax.swing.JButton();
        threePanel = new javax.swing.JPanel();
        threeRadioButton1 = new javax.swing.JRadioButton();
        threeRadioButton2 = new javax.swing.JRadioButton();
        threeRadioButton3 = new javax.swing.JRadioButton();
        threeRadioButton4 = new javax.swing.JRadioButton();
        fourPanel = new javax.swing.JPanel();
        fourCheckBox1 = new javax.swing.JCheckBox();
        fourCheckBox2 = new javax.swing.JCheckBox();
        fourCheckBox3 = new javax.swing.JCheckBox();
        fourCheckBox4 = new javax.swing.JCheckBox();
        fivePanel = new javax.swing.JPanel();
        fiveToggleButton1 = new javax.swing.JToggleButton();
        fiveToggleButton2 = new javax.swing.JToggleButton();
        fiveToggleButton3 = new javax.swing.JToggleButton();
        fiveToggleButton4 = new javax.swing.JToggleButton();
        sixPanel = new javax.swing.JPanel();
        sixComboBox1 = new javax.swing.JComboBox<>();
        sixUpdateButton = new javax.swing.JButton();
        sixDeleteButton = new javax.swing.JButton();
        sixAddButton = new javax.swing.JButton();
        sevenPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sevenList1 = new javax.swing.JList<>();
        sevenAddButton = new javax.swing.JButton();
        sevenTextField1 = new javax.swing.JTextField();
        sevenDeleteButton = new javax.swing.JButton();
        sevenUpdateButton = new javax.swing.JButton();
        eightPanel = new javax.swing.JPanel();
        eightSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FramePanelControls");

        onePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("one"));

        oneLabel.setText("init label");

        oneButton.setText("TextField => Label");
        oneButton.setToolTipText("");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        oneTextArea1.setColumns(20);
        oneTextArea1.setRows(5);
        oneTextArea1.setText("Text Area");
        oneTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneTextArea1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(oneTextArea1);

        javax.swing.GroupLayout onePanelLayout = new javax.swing.GroupLayout(onePanel);
        onePanel.setLayout(onePanelLayout);
        onePanelLayout.setHorizontalGroup(
            onePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(onePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(oneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oneTextField)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        onePanelLayout.setVerticalGroup(
            onePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onePanelLayout.createSequentialGroup()
                .addComponent(oneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        twoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("two"));

        twoLabel.setText("jLabel1");

        twoButton1.setText("Button1");
        twoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButton1ActionPerformed(evt);
            }
        });

        twoButton2.setText("Button2");
        twoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButton2ActionPerformed(evt);
            }
        });

        twoButton3.setText("Button3");
        twoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout twoPanelLayout = new javax.swing.GroupLayout(twoPanel);
        twoPanel.setLayout(twoPanelLayout);
        twoPanelLayout.setHorizontalGroup(
            twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(twoButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(twoButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twoButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        twoPanelLayout.setVerticalGroup(
            twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(twoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        threePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("three"));

        radioButtonGroup1.add(threeRadioButton1);
        threeRadioButton1.setSelected(true);
        threeRadioButton1.setText("jRadioButton1");
        threeRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRadioButton1ActionPerformed(evt);
            }
        });

        radioButtonGroup1.add(threeRadioButton2);
        threeRadioButton2.setText("jRadioButton2");
        threeRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRadioButton2ActionPerformed(evt);
            }
        });

        radioButtonGroup1.add(threeRadioButton3);
        threeRadioButton3.setText("jRadioButton3");
        threeRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRadioButton3ActionPerformed(evt);
            }
        });

        radioButtonGroup1.add(threeRadioButton4);
        threeRadioButton4.setText("jRadioButton4");
        threeRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout threePanelLayout = new javax.swing.GroupLayout(threePanel);
        threePanel.setLayout(threePanelLayout);
        threePanelLayout.setHorizontalGroup(
            threePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(threePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threeRadioButton1)
                    .addComponent(threeRadioButton2)
                    .addComponent(threeRadioButton3)
                    .addComponent(threeRadioButton4))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        threePanelLayout.setVerticalGroup(
            threePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threeRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threeRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threeRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threeRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("four"));

        fourCheckBox1.setText("jCheckBox1");
        fourCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCheckBox1ActionPerformed(evt);
            }
        });

        fourCheckBox2.setText("jCheckBox2");
        fourCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCheckBox2ActionPerformed(evt);
            }
        });

        fourCheckBox3.setText("jCheckBox3");
        fourCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCheckBox3ActionPerformed(evt);
            }
        });

        fourCheckBox4.setText("jCheckBox4");
        fourCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fourPanelLayout = new javax.swing.GroupLayout(fourPanel);
        fourPanel.setLayout(fourPanelLayout);
        fourPanelLayout.setHorizontalGroup(
            fourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fourCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
            .addComponent(fourCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fourCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fourCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fourPanelLayout.setVerticalGroup(
            fourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fourCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fivePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("five"));

        toggleButtonGroup1.add(fiveToggleButton1);
        fiveToggleButton1.setText("jToggleButton1");
        fiveToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveToggleButton1ActionPerformed(evt);
            }
        });

        toggleButtonGroup1.add(fiveToggleButton2);
        fiveToggleButton2.setText("jToggleButton2");
        fiveToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveToggleButton2ActionPerformed(evt);
            }
        });

        toggleButtonGroup1.add(fiveToggleButton3);
        fiveToggleButton3.setText("jToggleButton3");
        fiveToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveToggleButton3ActionPerformed(evt);
            }
        });

        toggleButtonGroup1.add(fiveToggleButton4);
        fiveToggleButton4.setText("jToggleButton4");
        fiveToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fivePanelLayout = new javax.swing.GroupLayout(fivePanel);
        fivePanel.setLayout(fivePanelLayout);
        fivePanelLayout.setHorizontalGroup(
            fivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fivePanelLayout.createSequentialGroup()
                        .addComponent(fiveToggleButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fivePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(fivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiveToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fiveToggleButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fiveToggleButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        fivePanelLayout.setVerticalGroup(
            fivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fiveToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiveToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiveToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiveToggleButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("six"));

        sixComboBox1.setEditable(true);
        sixComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "apple", "banana", "orange", "1234" }));
        sixComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixComboBox1ActionPerformed(evt);
            }
        });

        sixUpdateButton.setText("UPDATE");
        sixUpdateButton.setEnabled(false);

        sixDeleteButton.setText("DELETE");
        sixDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixDeleteButtonActionPerformed(evt);
            }
        });

        sixAddButton.setText("ADD");
        sixAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sixPanelLayout = new javax.swing.GroupLayout(sixPanel);
        sixPanel.setLayout(sixPanelLayout);
        sixPanelLayout.setHorizontalGroup(
            sixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sixComboBox1, 0, 114, Short.MAX_VALUE)
                    .addComponent(sixUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sixDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sixAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sixPanelLayout.setVerticalGroup(
            sixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sixComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sixAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sixUpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sixDeleteButton)
                .addContainerGap())
        );

        sevenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("seven"));

        sevenList1.setModel(new javax.swing.DefaultListModel<>());
        sevenList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenList1MouseClicked(evt);
            }
        });
        sevenList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sevenList1ValueChanged(evt);
            }
        });

        sevenAddButton.setText("ADD");
        sevenAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenAddButtonActionPerformed(evt);
            }
        });

        sevenDeleteButton.setText("DELETE");
        sevenDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenDeleteButtonActionPerformed(evt);
            }
        });

        sevenUpdateButton.setText("UPDATE");
        sevenUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sevenPanelLayout = new javax.swing.GroupLayout(sevenPanel);
        sevenPanel.setLayout(sevenPanelLayout);
        sevenPanelLayout.setHorizontalGroup(
            sevenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sevenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sevenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sevenTextField1)
                    .addComponent(sevenAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sevenPanelLayout.setVerticalGroup(
            sevenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sevenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sevenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(sevenPanelLayout.createSequentialGroup()
                        .addComponent(sevenTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sevenAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sevenDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sevenUpdateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("eight"));

        eightSlider.setMajorTickSpacing(20);
        eightSlider.setPaintLabels(true);
        eightSlider.setPaintTicks(true);
        eightSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                eightSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout eightPanelLayout = new javax.swing.GroupLayout(eightPanel);
        eightPanel.setLayout(eightPanelLayout);
        eightPanelLayout.setHorizontalGroup(
            eightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eightPanelLayout.setVerticalGroup(
            eightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eightPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(eightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sevenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(302, 302, 302))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(threePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sixPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fivePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sixPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        loggerMgr.getLogger().info("===> oneButtonActionPerformed()");
        oneLabel.setText(oneTextField.getText());
        //oneButton.setVisible(false);
        //oneTextField.setEnabled(false);
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButton1ActionPerformed
        loggerMgr.getLogger().info("===> twoButton1ActionPerformed()");
        twoLabel.setText(twoButton1.getText());
        
        int result = JOptionPane.showConfirmDialog(null, "무엇인가?", "확인", JOptionPane.YES_NO_OPTION);
        loggerMgr.getLogger().info("result = " + result);
    }//GEN-LAST:event_twoButton1ActionPerformed

    private void twoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButton2ActionPerformed
        loggerMgr.getLogger().info("===> twoButton2ActionPerformed()");
        twoLabel.setText(twoButton2.getText());
    }//GEN-LAST:event_twoButton2ActionPerformed

    private void twoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButton3ActionPerformed
        loggerMgr.getLogger().info("===> twoButton3ActionPerformed()");
        twoLabel.setText(twoButton3.getText());
    }//GEN-LAST:event_twoButton3ActionPerformed

    private void threeRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRadioButton1ActionPerformed
        loggerMgr.getLogger().info("===> threeRadioButton1ActionPerformed()");
        loggerMgr.getLogger().info("radiobutton1 1234= " + threeRadioButton1.isSelected());
        loggerMgr.getLogger().info("radiobutton2 abcd= " + threeRadioButton2.isSelected());
        loggerMgr.getLogger().info("radiobutton3 가나다라= " + threeRadioButton3.isSelected());
        loggerMgr.getLogger().info("radiobutton4 = " + threeRadioButton4.isSelected());
    }//GEN-LAST:event_threeRadioButton1ActionPerformed

    private void threeRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRadioButton2ActionPerformed
        loggerMgr.getLogger().info("===> threeRadioButton2ActionPerformed()");
        loggerMgr.getLogger().info("radiobutton1 = " + threeRadioButton1.isSelected());
        loggerMgr.getLogger().info("radiobutton2 = " + threeRadioButton2.isSelected());
        loggerMgr.getLogger().info("radiobutton3 = " + threeRadioButton3.isSelected());
        loggerMgr.getLogger().info("radiobutton4 = " + threeRadioButton4.isSelected());
    }//GEN-LAST:event_threeRadioButton2ActionPerformed

    private void threeRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRadioButton3ActionPerformed
        loggerMgr.getLogger().info("===> threeRadioButton3ActionPerformed()");
        loggerMgr.getLogger().info("radiobutton1 = " + threeRadioButton1.isSelected());
        loggerMgr.getLogger().info("radiobutton2 = " + threeRadioButton2.isSelected());
        loggerMgr.getLogger().info("radiobutton3 = " + threeRadioButton3.isSelected());
        loggerMgr.getLogger().info("radiobutton4 = " + threeRadioButton4.isSelected());
    }//GEN-LAST:event_threeRadioButton3ActionPerformed

    private void threeRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRadioButton4ActionPerformed
        loggerMgr.getLogger().info("===> threeRadioButton4ActionPerformed()");
        loggerMgr.getLogger().info("radiobutton1 = " + threeRadioButton1.isSelected());
        loggerMgr.getLogger().info("radiobutton2 = " + threeRadioButton2.isSelected());
        loggerMgr.getLogger().info("radiobutton3 = " + threeRadioButton3.isSelected());
        loggerMgr.getLogger().info("radiobutton4 = " + threeRadioButton4.isSelected());
    }//GEN-LAST:event_threeRadioButton4ActionPerformed

    private void fourCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCheckBox1ActionPerformed
        loggerMgr.getLogger().info("===> fourCheckBox1ActionPerformed()");
        loggerMgr.getLogger().info("fourCheckBox1 = " + fourCheckBox1.isSelected());
        loggerMgr.getLogger().info("fourCheckBox2 = " + fourCheckBox2.isSelected());
        loggerMgr.getLogger().info("fourCheckBox3 = " + fourCheckBox3.isSelected());
        loggerMgr.getLogger().info("fourCheckBox4 = " + fourCheckBox4.isSelected());
    }//GEN-LAST:event_fourCheckBox1ActionPerformed

    private void fourCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCheckBox2ActionPerformed
        loggerMgr.getLogger().info("===> fourCheckBox2ActionPerformed()");
        loggerMgr.getLogger().info("fourCheckBox1 = " + fourCheckBox1.isSelected());
        loggerMgr.getLogger().info("fourCheckBox2 = " + fourCheckBox2.isSelected());
        loggerMgr.getLogger().info("fourCheckBox3 = " + fourCheckBox3.isSelected());
        loggerMgr.getLogger().info("fourCheckBox4 = " + fourCheckBox4.isSelected());
    }//GEN-LAST:event_fourCheckBox2ActionPerformed

    private void fourCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCheckBox3ActionPerformed
        loggerMgr.getLogger().info("===> fourCheckBox3ActionPerformed()");
        loggerMgr.getLogger().info("fourCheckBox1 = " + fourCheckBox1.isSelected());
        loggerMgr.getLogger().info("fourCheckBox2 = " + fourCheckBox2.isSelected());
        loggerMgr.getLogger().info("fourCheckBox3 = " + fourCheckBox3.isSelected());
        loggerMgr.getLogger().info("fourCheckBox4 = " + fourCheckBox4.isSelected());
    }//GEN-LAST:event_fourCheckBox3ActionPerformed

    private void fourCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCheckBox4ActionPerformed
        loggerMgr.getLogger().info("===> fourCheckBox4ActionPerformed()");
        loggerMgr.getLogger().info("fourCheckBox1 = " + fourCheckBox1.isSelected());
        loggerMgr.getLogger().info("fourCheckBox2 = " + fourCheckBox2.isSelected());
        loggerMgr.getLogger().info("fourCheckBox3 = " + fourCheckBox3.isSelected());
        loggerMgr.getLogger().info("fourCheckBox4 = " + fourCheckBox4.isSelected());
    }//GEN-LAST:event_fourCheckBox4ActionPerformed

    private void fiveToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveToggleButton1ActionPerformed
        loggerMgr.getLogger().info("===> fiveToggleButton1ActionPerformed()");
        loggerMgr.getLogger().info("fiveToggleButton1 = " + fiveToggleButton1.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton2 = " + fiveToggleButton2.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton3 = " + fiveToggleButton3.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton4 = " + fiveToggleButton4.isSelected());
    }//GEN-LAST:event_fiveToggleButton1ActionPerformed

    private void fiveToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveToggleButton2ActionPerformed
        loggerMgr.getLogger().info("===> fiveToggleButton2ActionPerformed()");
        loggerMgr.getLogger().info("fiveToggleButton1 = " + fiveToggleButton1.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton2 = " + fiveToggleButton2.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton3 = " + fiveToggleButton3.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton4 = " + fiveToggleButton4.isSelected());
    }//GEN-LAST:event_fiveToggleButton2ActionPerformed

    private void fiveToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveToggleButton3ActionPerformed
        loggerMgr.getLogger().info("===> fiveToggleButton3ActionPerformed()");
        loggerMgr.getLogger().info("fiveToggleButton1 = " + fiveToggleButton1.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton2 = " + fiveToggleButton2.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton3 = " + fiveToggleButton3.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton4 = " + fiveToggleButton4.isSelected());
    }//GEN-LAST:event_fiveToggleButton3ActionPerformed

    private void fiveToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveToggleButton4ActionPerformed
        loggerMgr.getLogger().info("===> fiveToggleButton4ActionPerformed()");
        loggerMgr.getLogger().info("fiveToggleButton1 = " + fiveToggleButton1.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton2 = " + fiveToggleButton2.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton3 = " + fiveToggleButton3.isSelected());
        loggerMgr.getLogger().info("fiveToggleButton4 = " + fiveToggleButton4.isSelected());
    }//GEN-LAST:event_fiveToggleButton4ActionPerformed

    private void sixComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixComboBox1ActionPerformed
        loggerMgr.getLogger().info("===> sixComboBox1ActionPerformed()");
        loggerMgr.getLogger().info("index = " + sixComboBox1.getSelectedIndex());
        loggerMgr.getLogger().info("item = " + sixComboBox1.getSelectedItem());
    }//GEN-LAST:event_sixComboBox1ActionPerformed

    private void sixAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixAddButtonActionPerformed
        loggerMgr.getLogger().info("===> sixAddButtonActionPerformed()");
        sixComboBox1.addItem((String)sixComboBox1.getSelectedItem());        
    }//GEN-LAST:event_sixAddButtonActionPerformed

    private void sixDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixDeleteButtonActionPerformed
        loggerMgr.getLogger().info("===> sixDeleteButtonActionPerformed()");
        sixComboBox1.removeItem((String)sixComboBox1.getSelectedItem());
    }//GEN-LAST:event_sixDeleteButtonActionPerformed

    private void sevenList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sevenList1ValueChanged
        loggerMgr.getLogger().info("===> sevenList1ValueChanged()");

        // evt.getValueIsAdjusting()	true일 때 중간 상태, false일 때 확정
        if (evt.getValueIsAdjusting() == false) {
            loggerMgr.getLogger().info("단일 index = " + sevenList1.getSelectedIndex());
            loggerMgr.getLogger().info("단일 value = " + sevenList1.getSelectedValue());

            //loggerMgr.getLogger().info("멀티 index = " + sevenList1.getSelectedIndices());
            boolean first = true;
            String log = "";
            for (int index : sevenList1.getSelectedIndices()) {
                if (first == true) {
                    first = false;
                    log += index;
                } else {
                    log += ", " + index;
                }
            }
            loggerMgr.getLogger().info("멀티 index = [" + log + "]");
            loggerMgr.getLogger().info("멀티 value = " + sevenList1.getSelectedValuesList());
        }
    }//GEN-LAST:event_sevenList1ValueChanged

    private void sevenList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenList1MouseClicked
        loggerMgr.getLogger().info("===> sevenList1MouseClicked()");

        int index;
        String value;
        if (evt.getClickCount() == 2) {
            index = sevenList1.locationToIndex(evt.getPoint());
            value = (String) sevenList1.getModel().getElementAt(index);

            loggerMgr.getLogger().info("더블클릭, index = " + index + ", value = " + value);
        }
        
    }//GEN-LAST:event_sevenList1MouseClicked

    private void sevenAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenAddButtonActionPerformed
        loggerMgr.getLogger().info("===> sevenAddButtonActionPerformed()");
        
        DefaultListModel<String> model = (DefaultListModel<String>) sevenList1.getModel();
        String inputText = sevenTextField1.getText();
        loggerMgr.getLogger().info("inputText = " + inputText);
        
        if (inputText.length() > 0) {
            model.addElement(inputText);
        } else {
            JOptionPane.showMessageDialog(null, "데이터를 입력하세요");
        }        
    }//GEN-LAST:event_sevenAddButtonActionPerformed

    private void sevenDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenDeleteButtonActionPerformed
        loggerMgr.getLogger().info("===> sevenDeleteButtonActionPerformed()");
        
        DefaultListModel<String> model = (DefaultListModel<String>) sevenList1.getModel();
        
//        int index = sevenList1.getSelectedIndex();               
//        loggerMgr.getLogger().info("index = " + index);
//        model.remove(index);                

        // 점위로 할때는 내림차순으로 해야 인덱스가 안꼬이고 잘 됨
        int[] index = sevenList1.getSelectedIndices();
        // 오름차순 정렬
        Arrays.sort(index);
        
        if (sevenList1.getValueIsAdjusting() == false) {
            // 내림차순으로 삭제
            for (int i = index.length - 1; i >= 0; i -= 1) {
                loggerMgr.getLogger().info("remove idx = " + index[i]);
                model.remove(index[i]);
            }

            // 인덱스가 밀림
//        for (int i = 0; i < index.length; i += 1) {
//            loggerMgr.getLogger().info("remove idx = " + index[i]);
//            model.remove(index[i]);
//        }
        }
    }//GEN-LAST:event_sevenDeleteButtonActionPerformed

    private void sevenUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenUpdateButtonActionPerformed
        loggerMgr.getLogger().info("===> sevenDeleteButtonActionPerformed()");
        
        String inputText = sevenTextField1.getText();
        DefaultListModel<String> model = (DefaultListModel<String>) sevenList1.getModel();
        
        if (sevenList1.getValueIsAdjusting() == false) {
            if (inputText.length() > 0) {
                int idx = sevenList1.getSelectedIndex();
                model.set(idx, inputText);
            } else {
                JOptionPane.showMessageDialog(null, "데이터를 입력하세요");
            }
        }
    }//GEN-LAST:event_sevenUpdateButtonActionPerformed

    private void oneTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneTextArea1MouseClicked
        loggerMgr.getLogger().info("===> oneTextArea1MouseClicked()");
        
        String text = oneTextArea1.getText();
        if (evt.getClickCount() == 2) {
            loggerMgr.getLogger().info("더블 클릭, text = " + text);
        } else {
            if (SwingUtilities.isLeftMouseButton(evt) == true) {
                loggerMgr.getLogger().info("좌 클릭, text = " + text);
            } else if (SwingUtilities.isRightMouseButton(evt) == true) {
                loggerMgr.getLogger().info("우 클릭, text = " + text);
            } else {
                loggerMgr.getLogger().info("뭐지 클릭, text = " + text);
            }
        }
    }//GEN-LAST:event_oneTextArea1MouseClicked

    private void eightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_eightSliderStateChanged
        loggerMgr.getLogger().info("===> oneTextArea1MouseClicked()");
        
        eightSlider.setMinorTickSpacing(2);
        
        loggerMgr.getLogger().info("value = " + eightSlider.getValue());
        
        
    }//GEN-LAST:event_eightSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePanelControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePanelControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePanelControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePanelControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>
        //</editor-fold>
        
        //System.out.println(FramePanelControls.class.getName() + ", main()");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePanelControls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eightPanel;
    private javax.swing.JSlider eightSlider;
    private javax.swing.JPanel fivePanel;
    private javax.swing.JToggleButton fiveToggleButton1;
    private javax.swing.JToggleButton fiveToggleButton2;
    private javax.swing.JToggleButton fiveToggleButton3;
    private javax.swing.JToggleButton fiveToggleButton4;
    private javax.swing.JCheckBox fourCheckBox1;
    private javax.swing.JCheckBox fourCheckBox2;
    private javax.swing.JCheckBox fourCheckBox3;
    private javax.swing.JCheckBox fourCheckBox4;
    private javax.swing.JPanel fourPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton oneButton;
    private javax.swing.JLabel oneLabel;
    private javax.swing.JPanel onePanel;
    private javax.swing.JTextArea oneTextArea1;
    private javax.swing.JTextField oneTextField;
    private javax.swing.ButtonGroup radioButtonGroup1;
    private javax.swing.JButton sevenAddButton;
    private javax.swing.JButton sevenDeleteButton;
    private javax.swing.JList<String> sevenList1;
    private javax.swing.JPanel sevenPanel;
    private javax.swing.JTextField sevenTextField1;
    private javax.swing.JButton sevenUpdateButton;
    private javax.swing.JButton sixAddButton;
    private javax.swing.JComboBox<String> sixComboBox1;
    private javax.swing.JButton sixDeleteButton;
    private javax.swing.JPanel sixPanel;
    private javax.swing.JButton sixUpdateButton;
    private javax.swing.JPanel threePanel;
    private javax.swing.JRadioButton threeRadioButton1;
    private javax.swing.JRadioButton threeRadioButton2;
    private javax.swing.JRadioButton threeRadioButton3;
    private javax.swing.JRadioButton threeRadioButton4;
    private javax.swing.ButtonGroup toggleButtonGroup1;
    private javax.swing.JButton twoButton1;
    private javax.swing.JButton twoButton2;
    private javax.swing.JButton twoButton3;
    private javax.swing.JLabel twoLabel;
    private javax.swing.JPanel twoPanel;
    // End of variables declaration//GEN-END:variables

   
}
