/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.netbeans.controls;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author P088454
 */
public class TreeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TreeFrame.class.getName());
    
    DefaultTreeModel treeModel;

    /**
     * Creates new form TreeFrame
     */
    public TreeFrame() {
        initComponents();
        
        Test();
    }
    
    private void Test() {
//        // 1. 루트와 자식 노드 생성
//        DefaultMutableTreeNode root = new DefaultMutableTreeNode("과일");
//        DefaultMutableTreeNode apple = new DefaultMutableTreeNode("사과");
//        DefaultMutableTreeNode banana = new DefaultMutableTreeNode("바나나");
//        root.add(apple);
//        root.add(banana);
//
//        // 2. 모델 생성 (루트 노드를 연결)
//        DefaultTreeModel model = new DefaultTreeModel(root);

        // 노드 생성, root도 포함됨
        //DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode();
        //DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("root");
        // case 1
        //DefaultMutableTreeNode handNode = new DefaultMutableTreeNode("손가락");
        //DefaultMutableTreeNode footNode = new DefaultMutableTreeNode("발가락");
        //rootNode.add(handNode);
        //rootNode.add(footNode);
        // case 2
        //rootNode.add(new DefaultMutableTreeNode("손가락"));
        //rootNode.add(new DefaultMutableTreeNode("발가락"));
        
        //treeModel = new DefaultTreeModel(rootNode);
        
        //myTree.setModel(treeModel);
        
        
        // 데이터 추가
        //rootNode.add(new DefaultMutableTreeNode("손가락"));
        //rootNode.add(new DefaultMutableTreeNode("발가락"));
        
        
        // list, table과 달리 모델 생성때 무조건 한개의 노드가 필요
        //DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("root");
        //treeModel = new DefaultTreeModel(rootNode);        
        treeModel =  new DefaultTreeModel(new DefaultMutableTreeNode("root"));
        
        myTree.setModel(treeModel);
        
        
        // 데이터 추가
        // case 1
        DefaultMutableTreeNode rootNode = (DefaultMutableTreeNode) treeModel.getRoot();
        rootNode.add(new DefaultMutableTreeNode("apple"));
        rootNode.add(new DefaultMutableTreeNode("bnana"));

        // case 2
        ((DefaultMutableTreeNode) treeModel.getRoot()).add(new DefaultMutableTreeNode("사과"));
        ((DefaultMutableTreeNode) treeModel.getRoot()).add(new DefaultMutableTreeNode("바나나"));
        
        
        //DefaultMutableTreeNode appleNode = (DefaultMutableTreeNode) root.getChildAt(0); // 첫 번째 자식
        ((DefaultMutableTreeNode)((DefaultMutableTreeNode) treeModel.getRoot()).getChildAt(0)).add(new DefaultMutableTreeNode("child-사과"));
        
        
        // 데이터 변경후에는 무조건 갱신
        treeModel.reload();
        
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(myTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TreeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree myTree;
    // End of variables declaration//GEN-END:variables
}
