/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.netbeans.newframe;

import java.util.Arrays;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import study.netbeans.common.logger.LoggerManager;

/**
 *
 * @author P088454
 */
public class MainFrame extends javax.swing.JFrame {
    
    private LoggerManager loggerMgr;    
    private Sub1Frame sub1Frame;
    private Sub2Frame sub2Frame;
    private Sub3Frame sub3Frame;
    
    private DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initLoggerManager();
        
        initComponents();
        loggerMgr.getLogger().info("===> initComponents()");  
        
        initFrame();
        
        initData();
        
        loggerMgr.getLogger().info("========== init end ==========");  
    }

    private void initLoggerManager() {
        loggerMgr = new LoggerManager(this.getClass().getName(), Level.INFO);
        loggerMgr.getLogger().info("===> initLoggerManager()");  
    }
    
    private void initFrame() {
        sub1Frame = new Sub1Frame(this);
        sub1Frame.setLocationRelativeTo(this);
        //sub1Frame.setVisible(true);
        
        sub2Frame = new Sub2Frame(this);
        sub2Frame.setLocationRelativeTo(this);
        //sub2Frame.setVisible(true);
        
        sub3Frame = new Sub3Frame(this);
        sub3Frame.setLocationRelativeTo(this);
        //sub3Frame.setVisible(true);
        
        loggerMgr.getLogger().info("===> initSubFrame()");  
    }
    
    private void initData() {
        list.setModel(listModel);
        
        listModel.addElement("main_0");
        listModel.addElement("main_1");
        listModel.addElement("main_2");
        listModel.addElement("main_3");
        
        loggerMgr.getLogger().info("===> initData()");  
    }
    
    public JList getList() {
        return list;
    }

    public DefaultListModel<String> getListModel() {
        return listModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        sub1FrameButton = new javax.swing.JButton();
        sub2FrameButton = new javax.swing.JButton();
        sub3FrameButton = new javax.swing.JButton();
        down = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        sub1DataButton = new javax.swing.JButton();
        sub2DataButton = new javax.swing.JButton();
        sub3DataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");

        top.setBorder(javax.swing.BorderFactory.createTitledBorder("프레임 이동"));

        sub1FrameButton.setText("Sub1 Frame");
        sub1FrameButton.setPreferredSize(new java.awt.Dimension(100, 40));
        sub1FrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1FrameButtonActionPerformed(evt);
            }
        });

        sub2FrameButton.setText("Sub2 Frame");
        sub2FrameButton.setPreferredSize(new java.awt.Dimension(100, 40));
        sub2FrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2FrameButtonActionPerformed(evt);
            }
        });

        sub3FrameButton.setText("Sub3 Frame");
        sub3FrameButton.setPreferredSize(new java.awt.Dimension(100, 40));
        sub3FrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3FrameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sub1FrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sub2FrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(sub3FrameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sub1FrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub2FrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub3FrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        down.setBorder(javax.swing.BorderFactory.createTitledBorder("데이터 이동"));

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        sub1DataButton.setText("Sub1 Data");
        sub1DataButton.setPreferredSize(new java.awt.Dimension(76, 40));
        sub1DataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1DataButtonActionPerformed(evt);
            }
        });

        sub2DataButton.setText("Sub2 Data");
        sub2DataButton.setPreferredSize(new java.awt.Dimension(76, 40));
        sub2DataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2DataButtonActionPerformed(evt);
            }
        });

        sub3DataButton.setText("Sub3 Data");
        sub3DataButton.setPreferredSize(new java.awt.Dimension(76, 40));
        sub3DataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3DataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downLayout = new javax.swing.GroupLayout(down);
        down.setLayout(downLayout);
        downLayout.setHorizontalGroup(
            downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sub1DataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sub2DataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sub3DataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        downLayout.setVerticalGroup(
            downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(downLayout.createSequentialGroup()
                        .addComponent(sub1DataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub2DataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sub3DataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub1FrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1FrameButtonActionPerformed
        loggerMgr.getLogger().info("===> sub1FrameButtonActionPerformed()");  
        
        this.setVisible(false);
        sub1Frame.setVisible(true);
    }//GEN-LAST:event_sub1FrameButtonActionPerformed

    private void sub2FrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2FrameButtonActionPerformed
        loggerMgr.getLogger().info("===> sub2FrameButtonActionPerformed()");  
        
        this.setVisible(false);
        sub2Frame.setVisible(true);
    }//GEN-LAST:event_sub2FrameButtonActionPerformed

    private void sub3FrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3FrameButtonActionPerformed
        loggerMgr.getLogger().info("===> sub3FrameButtonActionPerformed()");  
        
        this.setVisible(false);
        sub3Frame.setVisible(true);
    }//GEN-LAST:event_sub3FrameButtonActionPerformed

    private void sub1DataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1DataButtonActionPerformed
        loggerMgr.getLogger().info("===> sub1DataButtonActionPerformed()");  
        
        // 선택된 인덱스
        int[] index = list.getSelectedIndices();
        // 오름차순 정렬
        Arrays.sort(index);
        
        String selectData;
        
        if (list.getValueIsAdjusting() == false) {
            for (int i = index.length - 1; i >= 0; i -= 1) {
                //loggerMgr.getLogger().info("index = " + i);  
                selectData = listModel.getElementAt(index[i]);
                sub1Frame.getListModel().addElement(selectData);
                listModel.remove(index[i]);
            }
        }
    }//GEN-LAST:event_sub1DataButtonActionPerformed

    private void sub2DataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2DataButtonActionPerformed
        loggerMgr.getLogger().info("===> sub2DataButtonActionPerformed()");  
        
        // 선택된 인덱스
        int[] index = list.getSelectedIndices();
        // 오름차순 정렬
        Arrays.sort(index);
        
        String selectData;
        
        if (list.getValueIsAdjusting() == false) {
            for (int i = index.length - 1; i >= 0; i -= 1) {
                selectData = listModel.getElementAt(index[i]);
                sub2Frame.getListModel().addElement(selectData);
                listModel.remove(index[i]);
            }
        }
    }//GEN-LAST:event_sub2DataButtonActionPerformed

    private void sub3DataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3DataButtonActionPerformed
        loggerMgr.getLogger().info("===> sub3DataButtonActionPerformed()");  
        
        // 선택된 인덱스
        int[] index = list.getSelectedIndices();
        // 오름차순 정렬
        Arrays.sort(index);
        
        String selectData;
        
        if (list.getValueIsAdjusting() == false) {
            for (int i = index.length - 1; i >= 0; i -= 1) {
                selectData = listModel.getElementAt(index[i]);
                sub3Frame.getListModel().addElement(selectData);
                listModel.remove(index[i]);
            }
        }
    }//GEN-LAST:event_sub3DataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel down;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton sub1DataButton;
    private javax.swing.JButton sub1FrameButton;
    private javax.swing.JButton sub2DataButton;
    private javax.swing.JButton sub2FrameButton;
    private javax.swing.JButton sub3DataButton;
    private javax.swing.JButton sub3FrameButton;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
